{% set name = "maicos" %}
{% set version = "0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/maicos-{{ version }}.tar.gz
  sha256: 1a00a256897af2717106e48d255194c2a8d8842404824a8f32b227aed61cc466

build:
  skip: true  # [python_impl == 'pypy']
  skip: true  # [py<310]
  entry_points:
    - maicos = maicos.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - libgomp  # [linux]
  host:
    - python
    - cython >=0.28
    - packaging
    - numpy >=2.0.0
    - setuptools >=77
    - setuptools-git-versioning <2
    - versioneer
    - wheel
    - pip
  run:
    - python
    - mdacli >=0.1.28
    - mdanalysis >=2.8.0
    - typing_extensions

test:
  imports:
    - maicos
  commands:
    - pip check
    - maicos --help
  requires:
    - pip

about:
  home: https://www.maicos-analysis.org
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Analyse molecular dynamics simulations of interfacial and confined systems.
  description: MAICoS is an object-oriented python toolkit for analysing the structure and dynamics of interfacial and confined fluids from molecular simulations. Combined with MDAnalysis, MAICoS can be used to extract density profiles, dielectric constants, structure factors, or transport properties from trajectories files,
    including LAMMPS, GROMACS, CHARMM or NAMD data. MAICoS is open source and is released under the GNU general public license v3.0.
  doc_url: https://www.maicos-analysis.org
  dev_url: https://gitlab.com/maicos-devel/maicos

extra:
  recipe-maintainers:
    - srihas29
    - PicoCentauri
    - hejamu
