{% set name = "maicos" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15d242d638f15ab1fa8f8888df45b4f4e1a746529b33128b1555f45b839bc04f

build:
  number: 1
  skip: true  # [python_impl == 'pypy']
  skip: true  # [py>312]
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - libgomp  # [linux]

  host:
    - python
    - cython >=0.28
    - packaging
    - numpy >=2.0.0
    - setuptools >=43.0.0
    - setuptools-git-versioning <2
    - versioneer
    - wheel
    - pip
  run:
    - python
    - mdacli >=0.1.28
    - mdanalysis >=2.8.0
    - typing_extensions

test:
  imports:
    - maicos
  commands:
    - pip check
    - maicos --help
  requires:
    - pip

about:
  home: https://www.maicos-analysis.org
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Analyse molecular dynamics simulations of interfacial and confined systems.
  description: MAICoS is an object-oriented python toolkit for analysing the structure and dynamics of interfacial and confined fluids from molecular simulations. Combined with MDAnalysis, MAICoS can be used to extract density profiles, dielectric constants, structure factors, or transport properties from trajectories files,
    including LAMMPS, GROMACS, CHARMM or NAMD data. MAICoS is open source and is released under the GNU general public license v3.0.
  doc_url: https://www.maicos-analysis.org
  dev_url: https://gitlab.com/maicos-devel/maicos

extra:
  recipe-maintainers:
    - srihas29
    - PicoCentauri
    - hejamu
