{% set name = "maicos" %}
{% set version = "0.12" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/maicos-{{ version }}.tar.gz
  sha256: e28a56adf6c4614911a735e4344e8ccc6421891e60d917c3db06b0a524461f4c

build:
  noarch: python
  entry_points:
    - maicos = maicos.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - packaging
    - setuptools >=77
    - setuptools_scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - mdacli >=0.2
    - mdanalysis >=2.10.0

test:
  imports:
    - maicos
  commands:
    - pip check
    - maicos --help
    - pip list | grep -iE "^maicos\s+{{ version.replace('.', '\.') }}$"
  requires:
    - pip

about:
  home: https://www.maicos-analysis.org
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Analyse molecular dynamics simulations of interfacial and confined systems.
  description: MAICoS is an object-oriented python toolkit for analysing the structure and dynamics of interfacial and confined fluids from molecular simulations. Combined with MDAnalysis, MAICoS can be used to extract density profiles, dielectric constants, structure factors, or transport properties from trajectories files,
    including LAMMPS, GROMACS, CHARMM or NAMD data. MAICoS is open source and is released under the GNU general public license v3.0.
  doc_url: https://www.maicos-analysis.org
  dev_url: https://gitlab.com/maicos-devel/maicos

extra:
  recipe-maintainers:
    - srihas29
    - PicoCentauri
    - hejamu
